//! Typed i18n message catalog (RFC-031).
//!
//! Compile-time completeness: each locale module implements one
//! exhaustive `match` over [`MessageKey`]. Adding a key without adding
//! every translation fails the build — there is no runtime fallback
//! path to hide a missing string.
//!
//! Parameterized messages are plain functions (RFC-031 §5.3) so the
//! compiler also checks their arguments.

pub mod en;
pub mod ja;

use crate::state::location::SearchFolderScope;
use serde::{Deserialize, Serialize};

/// Supported UI locales. Default English; persisted in the catalog
/// under the `ui.locale` setting (read/written by `orbok`).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum Locale {
    #[default]
    En,
    Ja,
}

impl Locale {
    pub const ALL: &'static [Locale] = &[Locale::En, Locale::Ja];

    /// Setting string stored in `app_settings` (`"en"` / `"ja"`).
    pub fn as_str(&self) -> &'static str {
        match self {
            Locale::En => "en",
            Locale::Ja => "ja",
        }
    }

    pub fn parse(s: &str) -> Option<Locale> {
        match s {
            "en" => Some(Locale::En),
            "ja" => Some(Locale::Ja),
            _ => None,
        }
    }

    /// Detect the preferred locale from the operating system environment.
    /// Checks `LANG` and `LANGUAGE` in that order. Returns `None` if
    /// neither variable is set or contains a recognised language code.
    /// Japanese is recognised when the value starts with `ja` (e.g. `ja`,
    /// `ja_JP`, `ja_JP.UTF-8`).
    pub fn from_env() -> Option<Locale> {
        for var in &["LANG", "LANGUAGE"] {
            if let Ok(val) = std::env::var(var)
                && let Some(locale) = Self::parse_env_value(&val)
            {
                return Some(locale);
            }
        }
        None
    }

    #[cfg(test)]
    pub(crate) fn from_env_values(lang: Option<&str>, language: Option<&str>) -> Option<Locale> {
        [lang, language]
            .into_iter()
            .flatten()
            .find_map(Self::parse_env_value)
    }

    fn parse_env_value(value: &str) -> Option<Locale> {
        let lower = value.to_lowercase();
        if lower.starts_with("ja") {
            Some(Locale::Ja)
        } else if lower.starts_with("en") {
            Some(Locale::En)
        } else {
            None
        }
    }

    /// Self-described language name, shown in the language picker.
    pub fn display_name(&self) -> &'static str {
        match self {
            Locale::En => "English",
            Locale::Ja => "日本語",
        }
    }
}

/// Defines [`MessageKey`] and generates `ALL_KEYS` from the exact same
/// variant list, so a new key cannot exist without appearing in the
/// exhaustiveness-test coverage (Review 134 §4, Review 138 §3(a)).
/// Previously `ALL_KEYS` was a hand-maintained `pub const` next to the
/// enum in `tests.rs` and had silently drifted to cover 257 of 273
/// variants before this fix -- deriving both from one list makes that
/// drift impossible rather than merely caught by review.
macro_rules! message_keys {
    ($(
        $(#[$variant_meta:meta])*
        $variant:ident
    ),+ $(,)?) => {
        /// Every fixed UI string. One variant per string; views never embed
        /// literals (RFC-031 §6 rule 1).
        #[derive(Debug, Clone, Copy, PartialEq, Eq)]
        pub enum MessageKey {
            $(
                $(#[$variant_meta])*
                $variant,
            )+
        }

        /// Every `MessageKey` variant, generated by [`message_keys`] from
        /// the same list that defines the enum.
        pub const ALL_KEYS: &[MessageKey] = &[
            $(MessageKey::$variant),+
        ];
    };
}

message_keys! {
    // Application chrome
    AppTitle,
    LocalOnlyBadge,
    // Navigation
    NavSearch,
    NavSources,
    NavIndexing,
    NavStorage,
    NavModels,
    NavAi,
    NavSettings,
    // Search view
    SearchPlaceholder,
    SearchButton,
    SearchNoSourcesTitle,
    SearchNoSourcesBody,
    SearchAddSource,
    SearchNoResults,
    SearchKeywordOnlyNotice,
    SearchRunning,
    SearchSnippetUnavailable,
    // Sources view
    SourcesTitle,
    SourcesEmptyTitle,
    SourcesEmptyBody,
    SourcesAddFolder,
    SourcesStatusActive,
    SourcesStatusPaused,
    SourcesStatusMissing,
    SourcesPathInputPlaceholder,
    SourcesRecursiveHint,
    // Indexing view
    IndexingTitle,
    IndexingIdle,
    IndexingHealthIndexed,
    IndexingHealthStale,
    IndexingHealthFailed,
    IndexingHealthQueued,
    IndexingRunning,
    // Storage view
    StorageTitle,
    StorageIntro,
    StorageGroupSearchIndex,
    StorageGroupModels,
    StorageGroupCaches,
    StorageSafeCleanupHeading,
    StorageClearSnippets,
    StorageClearSearchCache,
    StorageDangerHeading,
    StorageResetCatalog,
    StorageResetWarning,
    // Models view
    ModelsTitle,
    ModelsEmbeddingRole,
    ModelsRerankerRole,
    ModelsStatusAvailable,
    ModelsStatusMissing,
    ModelsKeywordOnlyHint,
    ModelsVerification,
    // Settings view
    SettingsTitle,
    SettingsLanguageHeading,
    SettingsPrivacyHeading,
    SettingsAdvancedHeading,
    SettingsAdvancedOn,
    SettingsAdvancedOff,
    SettingsAdvancedHint,
    SettingsPrivacyLocalOnly,
    // Search modes (RFC-009 §8)
    SearchModeLabel,
    SearchModeAuto,
    SearchModeExact,
    SearchModeConceptual,
    SearchModeFast,
    // Match badges
    BadgeKeyword,
    BadgeSemantic,
    // Unreferenced: no current MatchBadge variant corresponds to this key.
    // Retained for a future hybrid-fusion result badge (RFC-009 RRF) rather
    // than deleted (Review 134 §6.1).
    BadgeFused,
    BadgeReranked,
    BadgeSourceStale,
    // Native dialog titles (RFC-052 §3, HANDOFF-052 §3 item 4)
    DialogAddSourceTitle,
    DialogChooseSearchFolderTitle,
    // Startup wizard (design §wizard)
    WizardTitleNotConfigured,
    WizardTitleFileMissing,
    WizardTitleValidating,
    WizardTitleReady,
    WizardBodyNotConfigured,
    WizardBodyFileMissing,
    WizardFilesNeededLabel,
    WizardDownloadHint,
    WizardPathInputPlaceholder,
    WizardActionLocate,
    WizardActionValidate,
    WizardActionUseModel,
    WizardActionContinue,
    WizardPathPlaceholder,
    WizardDownloadAction,
    WizardDownloadProgress,
    WizardActionSkip,
    WizardOr,
    WizardMissingMarker,
    WizardBack,
    WizardPreviousPathLabel,
    WizardValidationOk,
    WizardValidationFail,
    WizardReadyBody,
    ModelConsentTitle,
    ModelConsentBody,
    ModelConsentPrivacy,
    ModelConsentProvider,
    ModelConsentSource,
    ModelConsentRevision,
    ModelConsentExactSize,
    ModelConsentLicense,
    ModelConsentLocation,
    ModelConsentVerification,
    ModelTrustAppWillVerify,
    ModelTrustAppVerified,
    ModelTrustUserSupplied,
    ModelConsentConfirm,
    ModelConsentCancel,
    ModelArtifactTokenizer,
    ModelArtifactOnnx,
    ModelDeliveryStoreUnavailable,
    ModelDeliveryConnection,
    ModelDeliveryVerification,
    ModelDeliveryLocalStorage,
    ModelDeliveryInternalState,
    ModelPersistenceSaving,
    ModelPersistenceFailed,
    ModelPersistenceRetry,
    // Common actions
    NoticeDownloadFailTitle,
    NoticeDownloadFailBody,
    NoticeFolderFailTitle,
    NoticeFolderFailBody,
    NoticeSearchFailTitle,
    NoticeSearchFailBody,
    NoticeFilesMissingTitle,
    NoticeFilesMissingBody,
    NoticeFolderAddedTitle,
    NoticeFolderAddedBody,
    NoticeSearchReadyTitle,
    NoticeSearchReadyBody,
    NoticePreviewsClearedTitle,
    NoticePreviewsClearedBody,
    NoticeActionTryAgain,
    NoticeActionChooseFolder,
    SettingsThemeHeading,
    ThemeSystem,
    ThemeLight,
    ThemeDark,
    ThemeHighContrastLight,
    ThemeHighContrastDark,
    // RFC-035 inclusive design
    SettingsTextScaleHeading,
    TextScaleDefault,
    TextScaleLarge,
    TextScaleLarger,
    SettingsReduceMotion,
    SettingsReduceMotionHint,
    SettingsCvdNote,
    NoticeSensitiveSourceTitle,
    NoticeSensitiveSourceBody,
    NoticeDismiss,
    Cancel,
    Confirm,
    // RFC-041: Search, Narrow Results, Browse Around
    SearchNarrowResults,
    SearchNarrowedBy,
    SearchMoreWays,
    SearchClearFilters,
    SearchNoResultsFiltered,
    SearchNoResultsFilteredBody,
    SearchInThisFolder,
    SearchShowNearby,
    SearchShowSimilar,
    SearchResultsUpdating,
    // RFC-036 §14.2 (RFC-056 Slice 4): partial-readiness reminder while
    // background preparation continues. The interpolated §14.1 "preparing"/
    // "ready" lines are `preparing_folder_for_search`/`files_ready_for_search`
    // below, not `MessageKey` variants -- both need a runtime value baked in,
    // which a `&'static str` match arm cannot carry.
    SearchFilesStillPreparing,
    SearchResultsWillImprove,
    // RFC-041 filter labels
    FilterKind,
    FilterChanged,
    FilterSearchIn,
    FilterReadyStatus,
    FilterKindPdfs,
    FilterKindNotes,
    FilterKindCode,
    FilterKindDocuments,
    FilterKindSpreadsheets,
    FilterChangedToday,
    FilterChangedThisWeek,
    FilterChangedThisMonth,
    FilterChangedAnyTime,
    FilterAllFolders,
    // RFC-037: Source lifecycle
    SourceStateReady,
    SourceStatePreparing,
    SourceStateNeedsUpdate,
    SourceStatePaused,
    SourceStateFolderNotFound,
    SourceStateCannotOpen,
    SourceStateRemoved,
    SourceActionCheckAgain,
    SourceActionPrepareAgain,
    SourceActionChooseFolderAgain,
    SourceActionRemoveFromOrbok,
    SourceFolderNotFoundDetail,
    SourceFilesNotDeletedNotice,
    SourceManyFilesChanged,
    SourcePausePreparation,
    SourceResumePreparation,
    // RFC-038: Result trust badges and recovery
    TrustNeedsUpdate,
    TrustFileNotFound,
    TrustStillBeingPrepared,
    TrustPartlyPrepared,
    TrustCannotOpen,
    TrustActionPrepareAgain,
    TrustActionCheckFolder,
    TrustActionRemoveFromResults,
    TrustActionOpenAnyway,
    TrustActionShowInFolder,
    TrustActionViewDetails,
    TrustFileChangedDetail,
    TrustFileNotFoundDetail,
    TrustPartlyPreparedDetail,
    TrustScannedPdfDetail,
    TrustSomePagesDetail,
    TrustSizeLimitDetail,
    TrustCannotOpenDetail,
    // RFC-043: Model download readiness
    ModelCheckingFiles,
    ModelAlreadyReady,
    ModelNeedsDownload,
    ModelDownloadingBetterSearch,
    ModelFilesStayLocal,
    ModelDownloadFailed,
    ModelDownloadRetry,
    ModelRepairingFiles,
    ModelBasicSearchAvailable,
    ModelDownloadingWhatNeeded,
    // RFC-039: Privacy modes
    PrivacyTitle,
    PrivacyLocalOnlyStatement,
    PrivacyModeStandard,
    PrivacyModeStrict,
    PrivacyModePortable,
    PrivacyModeStrictDescription,
    PrivacyModePortableDescription,
    PrivacyRememberSearches,
    PrivacyRememberSearchesHint,
    PrivacySearchesDisabledStrict,
    PrivacyTemporaryPreviews,
    PrivacyTemporaryPreviewsHint,
    PrivacyClearPreviews,
    PrivacyEnableStrictConfirm,
    PrivacyEnableStrictBody,
    PrivacyTurnOn,
    PrivacyTurnOnAndClear,
    PrivacyFilesNotDeleted,
    PrivacyModelDownloadNote,
    // RFC-040: Diagnostics
    DiagnosticsTitle,
    DiagnosticsIntro,
    DiagnosticsCreateFile,
    DiagnosticsPreviewTitle,
    DiagnosticsIncludedLabel,
    DiagnosticsExcludedLabel,
    DiagnosticsOptInFolderNames,
    DiagnosticsOptInFolderNamesHint,
    DiagnosticsOptInSearchWords,
    DiagnosticsOptInSearchWordsHint,
    DiagnosticsFileCreated,
    DiagnosticsShowFile,
    DiagnosticsCreateFailed,
    // RFC-045: search-in-folder flow
    /// Label "Search in" shown before the folder chip.
    SearchInLabel,
    /// Placeholder shown when no folder is selected yet.
    SearchChooseFolder,
    /// Scope toggle label shown when current scope is FolderAndSubfolders:
    /// offers to switch to folder-only.
    SearchScopeOnly,
    /// Scope toggle label shown when current scope is FolderOnly: offers to
    /// switch to including subfolders.
    SearchScopeSubfolders,
    /// Header for the recent / remembered folder chip row.
    SearchRecentFoldersLabel,
    // RFC-042: search history
    /// Panel / section header.
    RecentSearchesLabel,
    /// Button on each history entry.
    SearchAgainButton,
    /// Status shown while restoring a history entry (RFC-042 §9 step 5).
    SearchingAgainStatus,
    /// Button to open the Recent searches panel.
    OpenRecentSearches,
    /// Button to clear all history entries.
    ClearRecentSearches,
    /// Confirmation dialog title.
    ClearRecentSearchesConfirmTitle,
    /// Confirmation dialog body (RFC-042 §11.6).
    ClearRecentSearchesConfirmBody,
    /// Success notice shown after clearing (RFC-042 §13.3).
    RecentSearchesClearedNotice,
    /// Settings toggle label (RFC-042 §11.5).
    RememberRecentSearches,
    /// Privacy sub-label when enabled (RFC-042 §14).
    RecentSearchesPrivacyNote,
    /// Privacy sub-label when strict privacy is on (RFC-042 §14).
    RecentSearchesStrictPrivacyNote,
    /// Shown when the history list is empty.
    NoRecentSearches,
    /// Notice when a filter was dropped on reopen (RFC-042 §9 step 3).
    DroppedFilterNotice,
    // Diagnostics bundle preview (RFC-040 §11.2). Not currently wired into
    // any view -- see diagnostics.rs's module comment.
    DiagnosticsAppVersion,
    DiagnosticsPlatformSummary,
    DiagnosticsFolderStatusCounts,
    DiagnosticsSearchPreparationStatus,
    DiagnosticsModelReadiness,
    DiagnosticsRedactedLogs,
    DiagnosticsDocuments,
    DiagnosticsSearchWords,
    DiagnosticsRawFolderPaths,
    DiagnosticsIncludedHeading,
    DiagnosticsNotIncludedHeading,
    DiagnosticsFolderNamesOptedIn,
}

/// Translate a fixed message. The per-locale functions are exhaustive
/// matches — completeness is enforced by the compiler.
pub fn tr(locale: Locale, key: MessageKey) -> &'static str {
    match locale {
        Locale::En => en::message(key),
        Locale::Ja => ja::message(key),
    }
}

/// Localized title for the native "add a folder as a source" dialog
/// (RFC-052 §3, HANDOFF-052 §3 item 4). `orbok-app` calls this instead of
/// embedding English display copy or resolving a `MessageKey` itself —
/// platform integrations request an already-localized string from this
/// boundary (RFC-052 §3).
pub fn dialog_title_add_source(locale: Locale) -> &'static str {
    tr(locale, MessageKey::DialogAddSourceTitle)
}

/// Localized title for the native "choose a folder to search" dialog
/// (RFC-045's search-location flow), on the same boundary rule as
/// [`dialog_title_add_source`].
pub fn dialog_title_choose_search_folder(locale: Locale) -> &'static str {
    tr(locale, MessageKey::DialogChooseSearchFolderTitle)
}

/// Localized labels for the RFC-040 §11.2 diagnostics bundle preview
/// (RFC-052 §3, §7 — "correct nearby stale user documentation revealed by
/// the same terminology review"). `orbok-app`'s `diagnostics.rs` is not a
/// native platform dialog the way `main.rs`'s `rfd` calls are, but it is
/// an `orbok-app` file producing user-visible preview text, so it requests
/// one batch of already-localized labels here rather than importing
/// `MessageKey` and matching on it itself — the same boundary reasoning as
/// [`dialog_title_add_source`], aggregated into one call instead of twelve
/// single-string functions since the caller needs all of them together.
pub struct DiagnosticsBundleLabels {
    pub app_version: &'static str,
    pub platform_summary: &'static str,
    pub folder_status_counts: &'static str,
    pub search_preparation_status: &'static str,
    pub model_readiness: &'static str,
    pub redacted_logs: &'static str,
    pub documents: &'static str,
    pub search_words: &'static str,
    pub raw_folder_paths: &'static str,
    pub included_heading: &'static str,
    pub not_included_heading: &'static str,
    pub folder_names_opted_in: &'static str,
}

pub fn diagnostics_bundle_labels(locale: Locale) -> DiagnosticsBundleLabels {
    DiagnosticsBundleLabels {
        app_version: tr(locale, MessageKey::DiagnosticsAppVersion),
        platform_summary: tr(locale, MessageKey::DiagnosticsPlatformSummary),
        folder_status_counts: tr(locale, MessageKey::DiagnosticsFolderStatusCounts),
        search_preparation_status: tr(locale, MessageKey::DiagnosticsSearchPreparationStatus),
        model_readiness: tr(locale, MessageKey::DiagnosticsModelReadiness),
        redacted_logs: tr(locale, MessageKey::DiagnosticsRedactedLogs),
        documents: tr(locale, MessageKey::DiagnosticsDocuments),
        search_words: tr(locale, MessageKey::DiagnosticsSearchWords),
        raw_folder_paths: tr(locale, MessageKey::DiagnosticsRawFolderPaths),
        included_heading: tr(locale, MessageKey::DiagnosticsIncludedHeading),
        not_included_heading: tr(locale, MessageKey::DiagnosticsNotIncludedHeading),
        folder_names_opted_in: tr(locale, MessageKey::DiagnosticsFolderNamesOptedIn),
    }
}

/// Render a localized "label: value" pair (RFC-052 §4 rule 3), replacing the
/// ad-hoc `format!("{}: {value}", tr(locale, ...))` shape previously repeated
/// at each call site. Both locales currently share the same shape; Phase 3
/// manual Japanese QA (HANDOFF-052 §4) is where that gets revisited if it
/// reads awkwardly, without another call-site-by-call-site refactor.
pub fn fmt_label_value(locale: Locale, label: &str, value: impl std::fmt::Display) -> String {
    match locale {
        Locale::En | Locale::Ja => format!("{label}: {value}"),
    }
}

/// A pre-rounded file size in MB, parenthesized for inline wizard display
/// (RFC-052 §4 rule 3). "MB" is not localized today — `model_exact_size` and
/// `model_bytes` use the same unlocalized unit in both locales — but this
/// takes `locale` anyway, matching `fmt_label_value`, so a future
/// locale-specific parenthesis/spacing convention (Review 135 §3) is a
/// one-line change here instead of another signature change plus call-site
/// edit.
pub fn wizard_file_size_mb(locale: Locale, mb: f64) -> String {
    match locale {
        Locale::En | Locale::Ja => format!("({mb:.1} MB)"),
    }
}

/// RFC-036 §14.1 (RFC-056 Slice 4): background preparation is running for a
/// specific folder. Named only when the caller can honestly attribute the
/// work to one folder -- `search_view` only calls this when exactly one
/// source exists, since `SourceCard.indexed`/`stale`/`failed` are never
/// updated after creation and cannot identify *which* of several sources is
/// still preparing.
pub fn preparing_folder_for_search(locale: Locale, folder: &str) -> String {
    match locale {
        Locale::En => format!("Preparing \"{folder}\" for search"),
        Locale::Ja => format!("「{folder}」の検索準備中"),
    }
}

/// RFC-036 §14.1 (RFC-056 Slice 4): background preparation has caught up --
/// `ready` is the current indexed count, sourced from the same aggregate
/// `IndexHealth` `Message::HealthUpdated` already carries.
pub fn files_ready_for_search(locale: Locale, ready: u64) -> String {
    match locale {
        Locale::En => format!("{ready} files ready. You can search now."),
        Locale::Ja => format!("{ready} 件のファイルが準備完了。今すぐ検索できます。"),
    }
}

/// Parameterized exact model size shown before RFC-050 download consent.
pub fn model_exact_size(locale: Locale, bytes: u64) -> String {
    let decimal_mb = bytes as f64 / 1_000_000.0;
    match locale {
        Locale::En => format!("{bytes} bytes ({decimal_mb:.1} MB)"),
        Locale::Ja => format!("{bytes} バイト ({decimal_mb:.1} MB)"),
    }
}

/// Parameterized current/total file position with completed-state clamping.
pub fn model_file_position(locale: Locale, files_done: u32, files_total: u32) -> String {
    if files_total == 0 {
        return match locale {
            Locale::En => "Preparing files".to_string(),
            Locale::Ja => "ファイルを準備中".to_string(),
        };
    }
    let current = files_done.saturating_add(1).min(files_total);
    match locale {
        Locale::En => format!("File {current} of {files_total}"),
        Locale::Ja => format!("ファイル {current}/{files_total}"),
    }
}

/// Parameterized byte progress with localized byte units and percentage.
pub fn model_transfer_progress(locale: Locale, bytes: u64, total: u64) -> String {
    let exact_bytes = bytes;
    let bytes = model_bytes(locale, exact_bytes);
    if total == 0 {
        return bytes;
    }
    let transferred = model_bytes(locale, total);
    let ratio = (exact_bytes as f64 / total as f64).clamp(0.0, 1.0);
    format!("{bytes} / {transferred} ({:.0}%)", ratio * 100.0)
}

fn model_bytes(locale: Locale, bytes: u64) -> String {
    if bytes >= 1_000_000 {
        format!("{:.1} MB", bytes as f64 / 1_000_000.0)
    } else if bytes >= 1_000 {
        format!("{:.0} KB", bytes as f64 / 1_000.0)
    } else {
        match locale {
            Locale::En => format!("{bytes} B"),
            Locale::Ja => format!("{bytes} バイト"),
        }
    }
}

/// Parameterized: source card summary line.
pub fn source_summary(locale: Locale, indexed: u64, stale: u64, failed: u64) -> String {
    match locale {
        Locale::En => format!("{indexed} indexed · {stale} stale · {failed} failed"),
        Locale::Ja => format!("インデックス済み {indexed} · 要更新 {stale} · 失敗 {failed}"),
    }
}

/// Parameterized: "3 results".
pub fn search_result_count(locale: Locale, count: usize) -> String {
    match locale {
        Locale::En => format!("{count} result{}", if count == 1 { "" } else { "s" }),
        Locale::Ja => format!("{count} 件の結果"),
    }
}

/// Locale-aware byte/storage size formatting (RFC-035 §5.5).
/// Routes views away from ad-hoc `format!("{gib:.3} GiB total")` calls.
pub fn fmt_gib(locale: Locale, gib: f64) -> String {
    match locale {
        Locale::En => format!("{gib:.3} GiB total"),
        Locale::Ja => format!("合計 {gib:.3} GiB"),
    }
}

/// Locale-aware MiB bucket formatting for the storage view friendly buckets.
pub fn fmt_mib_bucket(locale: Locale, label: &str, mib: f64) -> String {
    match locale {
        Locale::En => format!("  {label}: {mib:.1} MiB"),
        Locale::Ja => format!("  {label}: {mib:.1} MiB"),
    }
}

/// Locale-aware advanced storage row formatting (category + count).
pub fn fmt_storage_row(locale: Locale, category: &str, mib: f64, count: u64) -> String {
    match locale {
        Locale::En => format!("  {category}: {mib:.1} MiB ({count} items)"),
        Locale::Ja => format!("  {category}: {mib:.1} MiB（{count} 件）"),
    }
}

/// Locale-aware last-query display (search view "no results" state).
pub fn fmt_query(locale: Locale, query: &str) -> String {
    match locale {
        Locale::En => format!("Query: {query}"),
        Locale::Ja => format!("検索語: {query}"),
    }
}

/// Parameterized: the selected search-location chip label (RFC-045 §7.3,
/// §11.1), e.g. `Documents and subfolders` or `Documents only`. Keeps the
/// friendly "folder" wording — never "source" or "recursive" (RFC-045
/// §19.4).
pub fn search_location_chip(locale: Locale, folder: &str, scope: SearchFolderScope) -> String {
    match (locale, scope) {
        (Locale::En, SearchFolderScope::FolderAndSubfolders) => format!("{folder} and subfolders"),
        (Locale::En, SearchFolderScope::FolderOnly) => format!("{folder} only"),
        (Locale::Ja, SearchFolderScope::FolderAndSubfolders) => {
            format!("{folder} とサブフォルダー")
        }
        (Locale::Ja, SearchFolderScope::FolderOnly) => format!("{folder} のみ"),
    }
}
