#!/usr/bin/env bash
# scripts/package.sh — build a release archive for orbok.
#
# Usage:
#   ./scripts/package.sh <version>
#
# Example:
#   ./scripts/package.sh 0.17.0
#
# Output (written to dist/ at the repository root, never into the source tree):
#   dist/orbok-v0.17.0.tar.gz
#   dist/orbok-v0.17.0.tar.gz.sha256
#
# Archive layout (flat — no parent directory):
#   ./Cargo.toml
#   ./crates/
#   ./rfcs/
#   ...
#
# Excluded from the archive:
#   .git/          — version-control history
#   .git-exclude/  — local agent review/task artifacts
#   .agents/       — local agent configuration
#   .codex/        — local Codex configuration
#   target/        — build artifacts
#   docs/book/     — generated mdBook output
#   Cargo.lock     — regenerated by users on first build
#   dist/          — release output directory (this script's own output)
#   *.tar.gz       — any stray archives in the repo root
#   *.tar.gz.sha256 — any stray checksums in the repo root

set -euo pipefail

# ── Argument validation ────────────────────────────────────────────────
if [[ $# -ne 1 ]]; then
    echo "Usage: $0 <version>" >&2
    exit 1
fi
VERSION="$1"
ARCHIVE="orbok-v${VERSION}.tar.gz"

# ── Resolve paths ──────────────────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
DIST_DIR="${REPO_ROOT}/dist"
mkdir -p "${DIST_DIR}"

# ── Build archive ──────────────────────────────────────────────────────
# Write to a tmp path first, then move to dist/ — this avoids any risk
# of the output file appearing in the source tree during the tar run.
echo "Packaging orbok-v${VERSION} ..."
TMPARCHIVE="$(mktemp "${DIST_DIR}/orbok-pkg-XXXXXX.tar.gz")"
tar czf "${TMPARCHIVE}" \
    --exclude='.git' \
    --exclude='.git-exclude' \
    --exclude='.agents' \
    --exclude='.codex' \
    --exclude='target' \
    --exclude='docs/book' \
    --exclude='Cargo.lock' \
    --exclude='dist' \
    --exclude='*.tar.gz' \
    --exclude='*.tar.gz.sha256' \
    -C "${REPO_ROOT}" \
    .
mv "${TMPARCHIVE}" "${DIST_DIR}/${ARCHIVE}"

# ── Checksum ───────────────────────────────────────────────────────────
cd "${DIST_DIR}"
sha256sum "${ARCHIVE}" > "${ARCHIVE}.sha256"
echo "SHA-256: $(awk '{print $1}' "${ARCHIVE}.sha256")"

# ── Summary ────────────────────────────────────────────────────────────
echo ""
echo "Created:"
echo "  dist/${ARCHIVE}"
echo "  dist/${ARCHIVE}.sha256"
echo ""
echo "Archive layout (first 8 entries — flat, no parent directory):"
tar tf "${ARCHIVE}" | awk 'NR <= 8 { print }'
echo "  ..."
echo "  ($(tar tf "${ARCHIVE}" | wc -l) entries total)"
