#!/usr/bin/env bash
# scripts/package.test.sh — adversarial regression test for
# scripts/package.sh and scripts/verify-release-archive.sh (RFC-051 §8,
# HANDOFF-051 §4).
#
# Builds a throwaway git repository under a temp directory (touches
# nothing in this repo), seeds it with a minimal but representative
# tracked file set, and proves every property RFC-051 requires:
#   - clean packaging succeeds and the independent verifier agrees;
#   - untracked and ignored files never enter the archive and never
#     block packaging;
#   - a forbidden local-only path, even if force-tracked, is excluded;
#   - a filename containing spaces survives correctly;
#   - dirty tracked content blocks packaging;
#   - a tracked symlink blocks packaging;
#   - executable-bit preservation and stable ordinary-file modes;
#   - canonical `./` naming, single root entry, no duplicates;
#   - two clean builds are byte-identical;
#   - a planted producer/policy disagreement is caught by the verifier
#     independently -- the property RFC-051 §6 cares about most.
set -euo pipefail

repo_root="$(cd "$(dirname "$0")/.." && pwd)"
package_sh="$repo_root/scripts/package.sh"
policy_sh="$repo_root/scripts/release-path-policy.sh"
verify_sh="$repo_root/scripts/verify-release-archive.sh"

tmp_repo="$(mktemp -d)"
tmp_work="$(mktemp -d)"
trap 'rm -rf "$tmp_repo" "$tmp_work"' EXIT

fail=0
check() {
  local desc="$1" expected="$2" actual="$3"
  if [ "$actual" != "$expected" ]; then
    echo "FAIL: $desc (expected $expected, got $actual)" >&2
    fail=1
  else
    echo "ok: $desc"
  fi
}
check_true() {
  local desc="$1" cond="$2"
  if [ "$cond" = "true" ]; then
    echo "ok: $desc"
  else
    echo "FAIL: $desc" >&2
    fail=1
  fi
}

cd "$tmp_repo"
git init -q
git config user.email "test@example.invalid"
git config user.name "Test"

mkdir -p scripts crates docs rfcs
cp "$package_sh" scripts/package.sh
cp "$policy_sh" scripts/release-path-policy.sh
cp "$verify_sh" scripts/verify-release-archive.sh
chmod +x scripts/package.sh scripts/release-path-policy.sh scripts/verify-release-archive.sh

cat > Cargo.toml <<'EOF'
[workspace]
members = ["crates/fixture"]
EOF
mkdir -p crates/fixture/src
cat > crates/fixture/Cargo.toml <<'EOF'
[package]
name = "fixture"
version = "0.1.0"
edition = "2021"
EOF
echo 'fn main() {}' > crates/fixture/src/main.rs
cat > Cargo.lock <<'EOF'
# This file is automatically @generated by Cargo.
version = 3
EOF
echo "MIT" > LICENSE
echo "NOTICE" > NOTICE
echo "# fixture" > README.md
echo "doc" > docs/index.md
echo "rfc" > rfcs/001-fixture.md
# A tracked executable script, to test executable-bit preservation.
echo '#!/usr/bin/env bash' > scripts/run.sh
echo 'echo hi' >> scripts/run.sh
chmod 755 scripts/run.sh

git add -A
git commit -q -m "initial fixture tree"

run_package() {
  (cd "$tmp_repo" && bash scripts/package.sh "$1") 2>&1
}
run_verify() {
  (cd "$tmp_repo" && bash scripts/verify-release-archive.sh "dist/orbok-v$1.tar.gz") 2>&1
}

# ── Clean packaging succeeds, verifier agrees ─────────────────────────────
clean_pkg_status=0
clean_pkg_out="$(run_package 1.0.0)" || clean_pkg_status=$?
check "clean packaging exits 0" "0" "$clean_pkg_status"
clean_verify_status=0
clean_verify_out="$(run_verify 1.0.0)" || clean_verify_status=$?
check "independent verifier accepts the clean archive" "0" "$clean_verify_status"
if [ "$clean_verify_status" != "0" ]; then
  echo "$clean_pkg_out" >&2
  echo "$clean_verify_out" >&2
fi

# ── Untracked file: never enters the archive, never blocks packaging ─────
echo "untracked" > untracked-file.txt
untracked_pkg_status=0
run_package 1.0.1 >"$tmp_work/pkg-untracked.log" 2>&1 || untracked_pkg_status=$?
check "packaging succeeds with an untracked file present" "0" "$untracked_pkg_status"
in_archive="$(tar tf dist/orbok-v1.0.1.tar.gz | grep -c "untracked-file.txt" || true)"
check "untracked file is absent from the archive" "0" "$in_archive"
rm -f untracked-file.txt

# ── Ignored file: never enters the archive, never blocks packaging ───────
echo "*.ignored" > .gitignore
echo "secret" > local.ignored
git add .gitignore
git commit -q -m "add gitignore"
ignored_pkg_status=0
run_package 1.0.2 >"$tmp_work/pkg-ignored.log" 2>&1 || ignored_pkg_status=$?
check "packaging succeeds with an ignored file present" "0" "$ignored_pkg_status"
in_archive="$(tar tf dist/orbok-v1.0.2.tar.gz | grep -c "local.ignored" || true)"
check "ignored file is absent from the archive" "0" "$in_archive"
rm -f local.ignored

# ── Forbidden local-only path, force-tracked: excluded by policy anyway ──
mkdir -p .git-exclude
echo "local review notes" > .git-exclude/notes.md
git add -f .git-exclude/notes.md
git commit -q -m "accidentally track a local-only path"
forbidden_pkg_status=0
run_package 1.0.3 >"$tmp_work/pkg-forbidden.log" 2>&1 || forbidden_pkg_status=$?
check "packaging succeeds with a force-tracked forbidden path present" "0" "$forbidden_pkg_status"
in_archive="$(tar tf dist/orbok-v1.0.3.tar.gz | grep -c "\.git-exclude" || true)"
check "force-tracked forbidden path is excluded from the archive by policy" "0" "$in_archive"
git rm -rq .git-exclude
git commit -q -m "remove the accidentally-tracked path"

# ── Filename containing spaces ────────────────────────────────────────────
echo "spaced" > "docs/a file with spaces.md"
git add "docs/a file with spaces.md"
git commit -q -m "add a filename with spaces"
spaces_pkg_status=0
run_package 1.0.4 >"$tmp_work/pkg-spaces.log" 2>&1 || spaces_pkg_status=$?
check "packaging succeeds with a tracked filename containing spaces" "0" "$spaces_pkg_status"
in_archive="$(tar tf dist/orbok-v1.0.4.tar.gz | grep -c "^\./docs/a file with spaces\.md$" || true)"
check "the spaced filename is present, correctly, exactly once" "1" "$in_archive"
spaces_verify_status=0
run_verify 1.0.4 >"$tmp_work/verify-spaces.log" 2>&1 || spaces_verify_status=$?
check "independent verifier accepts the spaced-filename archive" "0" "$spaces_verify_status"

# ── Dirty tracked content blocks packaging ────────────────────────────────
echo "dirty" >> README.md
dirty_pkg_status=0
run_package 1.0.5 >"$tmp_work/pkg-dirty.log" 2>&1 || dirty_pkg_status=$?
check "packaging fails on dirty tracked content" "1" "$dirty_pkg_status"
git checkout -q -- README.md

# ── Tracked symlink blocks packaging ──────────────────────────────────────
ln -s README.md link-to-readme
git add link-to-readme
git commit -q -m "add a tracked symlink"
symlink_pkg_status=0
run_package 1.0.6 >"$tmp_work/pkg-symlink.log" 2>&1 || symlink_pkg_status=$?
check "packaging fails on a tracked symlink" "1" "$symlink_pkg_status"
git rm -q link-to-readme
git commit -q -m "remove the tracked symlink"

# ── Executable-bit preservation, canonical naming, no duplicates ─────────
final_pkg_status=0
final_pkg_out="$(run_package 2.0.0)" || final_pkg_status=$?
check "final clean packaging exits 0" "0" "$final_pkg_status"

exec_mode="$(tar tvf dist/orbok-v2.0.0.tar.gz 2>/dev/null | awk '$0 ~ /scripts\/run\.sh$/ { print $1 }')"
case "$exec_mode" in
  -rwxr-xr-x*) echo "ok: tracked executable script keeps its executable mode in the archive" ;;
  *) echo "FAIL: tracked executable script mode is '$exec_mode', expected -rwxr-xr-x*" >&2; fail=1 ;;
esac
ordinary_mode="$(tar tvf dist/orbok-v2.0.0.tar.gz 2>/dev/null | awk '$0 ~ /README\.md$/ { print $1 }')"
case "$ordinary_mode" in
  -rw-r--r--*) echo "ok: ordinary tracked file gets a stable non-executable mode" ;;
  *) echo "FAIL: ordinary file mode is '$ordinary_mode', expected -rw-r--r--*" >&2; fail=1 ;;
esac

root_entries="$(tar tf dist/orbok-v2.0.0.tar.gz | grep -c '^\./$' || true)"
check "exactly one canonical ./ root entry" "1" "$root_entries"
non_canonical="$(tar tf dist/orbok-v2.0.0.tar.gz | grep -vc '^\./' || true)"
check "every entry uses canonical ./ naming" "0" "$non_canonical"
dup_entries="$(tar tf dist/orbok-v2.0.0.tar.gz | sort | uniq -d | wc -l | tr -d ' ')"
check "no duplicate entries in the archive" "0" "$dup_entries"

# ── Two clean builds are byte-identical ───────────────────────────────────
sleep 1.1
run_package 2.0.1-a >"$tmp_work/pkg-repro-a.log" 2>&1
mv dist/orbok-v2.0.1-a.tar.gz "$tmp_work/repro-a.tar.gz"
sleep 1.1
run_package 2.0.1-b >"$tmp_work/pkg-repro-b.log" 2>&1
mv dist/orbok-v2.0.1-b.tar.gz "$tmp_work/repro-b.tar.gz"
# Rename both to the same name before hashing -- the archive filename
# differs (it embeds the version), the point is the *content* bytes match.
hash_a="$(sha256sum "$tmp_work/repro-a.tar.gz" | awk '{print $1}')"
hash_b="$(sha256sum "$tmp_work/repro-b.tar.gz" | awk '{print $1}')"
check "two clean builds of the same commit produce byte-identical archives" "$hash_a" "$hash_b"
rm -f "$tmp_work/repro-a.tar.gz" "$tmp_work/repro-b.tar.gz"

# ── Planted producer/policy disagreement: verifier catches it independently ──
# Craft a "bad" archive by hand: take the good one, add an extra file the
# policy never approved, using plain tar (bypassing package.sh entirely --
# this simulates a producer bug, not a policy change).
mkdir -p "$tmp_work/bad-archive-staging"
(cd "$tmp_work/bad-archive-staging" && tar xf "$tmp_repo/dist/orbok-v2.0.0.tar.gz")
echo "not reviewed" > "$tmp_work/bad-archive-staging"/unreviewed-extra-file.txt
tar -C "$tmp_work/bad-archive-staging" --format=pax --sort=name --owner=0 --group=0 --numeric-owner \
  -cf - . | gzip -n -9 > "$tmp_repo/dist/orbok-v2.0.0-tampered.tar.gz"
tampered_verify_status=0
(cd "$tmp_repo" && bash scripts/verify-release-archive.sh dist/orbok-v2.0.0-tampered.tar.gz) \
  >"$tmp_work/verify-tampered.log" 2>&1 || tampered_verify_status=$?
check "verifier rejects a tampered archive containing an unreviewed extra file" "1" "$tampered_verify_status"
if [ "$tampered_verify_status" = "1" ]; then
  grep -q "unreviewed-extra-file.txt" "$tmp_work/verify-tampered.log" \
    && echo "ok: verifier names the specific unreviewed file" \
    || { echo "FAIL: verifier did not name the unreviewed file" >&2; fail=1; }
fi
rm -rf "$tmp_work/bad-archive-staging"

# Same idea, the other direction: a file the policy requires is missing.
mkdir -p "$tmp_work/incomplete-archive-staging"
(cd "$tmp_work/incomplete-archive-staging" && tar xf "$tmp_repo/dist/orbok-v2.0.0.tar.gz")
rm -f "$tmp_work/incomplete-archive-staging"/NOTICE
tar -C "$tmp_work/incomplete-archive-staging" --format=pax --sort=name --owner=0 --group=0 --numeric-owner \
  -cf - . | gzip -n -9 > "$tmp_repo/dist/orbok-v2.0.0-incomplete.tar.gz"
incomplete_verify_status=0
(cd "$tmp_repo" && bash scripts/verify-release-archive.sh dist/orbok-v2.0.0-incomplete.tar.gz) \
  >"$tmp_work/verify-incomplete.log" 2>&1 || incomplete_verify_status=$?
check "verifier rejects an archive missing a policy-required file" "1" "$incomplete_verify_status"
rm -rf "$tmp_work/incomplete-archive-staging"

if [ "$fail" -ne 0 ]; then
  echo "package.test.sh: FAILED" >&2
  exit 1
fi
echo "package.test.sh: ok"
